In [1]:
import pandas as pd

In [3]:
fase_soja = ['floracao', 'enchimento_graos', 'colheita', 'pos_colheita', 'entressafra', 'preparacao_safra', 'pre_plantio'
             , 'plantio', 'desenvolvimento_vegetativo']

In [6]:
datas_semanais = pd.date_range(start='2016-01-01', end='2026-05-31', freq='W-FRI')

df = pd.DataFrame({
    'data_semana': datas_semanais,
    'mes': datas_semanais.month,
    'ano': datas_semanais.year
})

df.set_index('data_semana', inplace=True)
df.head()

             mes   ano
data_semana
2016-01-01     1  2016
2016-01-08     1  2016
2016-01-15     1  2016
2016-01-22     1  2016
2016-01-29     1  2016

In [7]:
month_to_fase = {
    9: fase_soja[6],  # pre_plantio
    10: fase_soja[7], # plantio
    11: fase_soja[8], # desenvolvimento_vegetativo
    12: fase_soja[8], # desenvolvimento_vegetativo
    1: fase_soja[0],  # floracao
    2: fase_soja[1],  # enchimento_graos
    3: fase_soja[2],  # colheita
    4: fase_soja[3],  # pos_colheita
    5: fase_soja[4],  # entressafra
    6: fase_soja[4],  # entressafra
    7: fase_soja[4],  # entressafra
    8: fase_soja[5]   # preparacao_safra
}

df['fase_soja'] = df['mes'].map(month_to_fase)
display(df.head())

             mes   ano fase_soja
data_semana
2016-01-01     1  2016  floracao
2016-01-08     1  2016  floracao
2016-01-15     1  2016  floracao
2016-01-22     1  2016  floracao
2016-01-29     1  2016  floracao

In [8]:
month_to_period = {
    9: 0,  # pre_plantio
    10: 1, # plantio
    11: 1, # desenvolvimento_vegetativo
    12: 1, # desenvolvimento_vegetativo
    1: 3,  # floracao
    2: 3,  # enchimento_graos
    3: 1,  # colheita
    4: 0,  # pos_colheita
    5: 0,  # entressafra
    6: 0,  # entressafra
    7: 0,  # entressafra
    8: 0   # preparacao_safra
}

df['periodo_critico_soja'] = df['mes'].map(month_to_period)
display(df.head())

             mes   ano fase_soja  periodo_critico_soja
data_semana
2016-01-01     1  2016  floracao                     3
2016-01-08     1  2016  floracao                     3
2016-01-15     1  2016  floracao                     3
2016-01-22     1  2016  floracao                     3
2016-01-29     1  2016  floracao                     3

In [9]:
df.to_parquet('df_calendario_agricola')