In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("dolar_ptax_raw.csv")
df.head()

         data   valor
0  2016-06-06  3.5098
1  2016-06-07  3.4745
2  2016-06-08  3.3898
3  2016-06-09  3.3817
4  2016-06-10  3.4261

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   data    2509 non-null   object
 1   valor   2509 non-null   float64
dtypes: float64(1), object(1)
memory usage: 39.3+ KB

In [4]:
df['data'] = pd.to_datetime(df['data'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   data    2509 non-null   datetime64[ns]
 1   valor   2509 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 39.3 KB

In [5]:
df.isnull().sum()

data     0
valor    0
dtype: int64

In [6]:
df.isna().sum()

data     0
valor    0
dtype: int64

## Exportando dados diarios

In [7]:
df.to_parquet('df_daily-dolarptax.parquet', index=False)

## Dataset semanal

In [9]:
df = df.set_index('data')
df.head()

             valor
data
2016-06-06  3.5098
2016-06-07  3.4745
2016-06-08  3.3898
2016-06-09  3.3817
2016-06-10  3.4261

In [12]:
df_weekly = (
    df
    .resample("W-FRI")
    .agg(
        dolar_medio_semana=("valor", "mean"),
        dolar_fechamento_semana=("valor", "last"),
        dolar_max_semana=("valor", "max"),
        dolar_min_semana=("valor", "min"),
    )
)

In [13]:
df_weekly.head()

,dolar_medio_semana,dolar_fechamento_semana,dolar_max_semana,dolar_min_semana
data,,,,
2016-06-10,3.43638,3.4261,3.5098,3.3817
2016-06-17,3.46832,3.4372,3.4904,3.4372
2016-06-24,3.37840,3.3772,3.3897,3.3533
2016-07-01,3.28064,3.2298,3.3934,3.2098
2016-07-08,3.29964,3.2968,3.3388,3.2480

In [16]:
df_weekly.to_parquet('df_weekly-dolarptax.parquet', index=True)