# **Imports**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# **CEPEA**

In [2]:
cepea = pd.read_parquet('df_weekly-cepea.parquet')
cepea.head()

,indicador,semana,preco_rs_medio,preco_rs_fechamento,preco_rs_max,preco_rs_min,preco_usd_medio,preco_usd_fechamento,preco_usd_max,preco_usd_min,qtd_dias_semana,retorno_rs_1w,retorno_usd_1w
0,parana,2016-01-15,80.298,79.79,80.76,79.79,19.940,19.70,20.22,19.70,5,0.010512,0.006643
1,paranagua,2016-01-15,84.822,84.42,85.70,83.35,21.066,20.85,21.39,20.59,5,0.015152,0.011645
2,paranagua,2016-01-22,83.220,82.94,83.98,82.39,20.344,20.19,20.83,20.02,5,-0.017531,-0.031655
3,parana,2016-01-22,78.294,77.81,79.55,77.81,19.144,18.95,19.74,18.78,5,-0.024815,-0.038071
4,parana,2016-01-29,76.572,75.64,77.28,75.64,18.812,18.79,18.92,18.67,5,-0.027888,-0.008443

In [3]:
cepea.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1086 entries, 0 to 1085
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   indicador             1086 non-null   object
 1   semana                1086 non-null   datetime64[ns]
 2   preco_rs_medio        1086 non-null   float64
 3   preco_rs_fechamento   1086 non-null   float64
 4   preco_rs_max          1086 non-null   float64
 5   preco_rs_min          1086 non-null   float64
 6   preco_usd_medio       1086 non-null   float64
 7   preco_usd_fechamento  1086 non-null   float64
 8   preco_usd_max         1086 non-null   float64
 9   preco_usd_min         1086 non-null   float64
 10  qtd_dias_semana       1086 non-null   int64
 11  retorno_rs_1w         1086 non-null   float64
 12  retorno_usd_1w        1086 non-null   float64
dtypes: datetime64[ns](1), float64(10), int64(1), object(1)
memory usage: 110.4+ KB

In [4]:
cepea.shape

(1086, 13)

In [5]:
print(cepea['indicador'].value_counts())

indicador
parana       543
paranagua    543
Name: count, dtype: int64

In [6]:
print(cepea['semana'].min(), cepea['semana'].max())

2016-01-15 00:00:00 2026-06-05 00:00:00

In [7]:
print(cepea['preco_rs_medio'].min())

59.948

In [8]:
cepea.isna().sum()

indicador               0
semana                  0
preco_rs_medio          0
preco_rs_fechamento     0
preco_rs_max            0
preco_rs_min            0
preco_usd_medio         0
preco_usd_fechamento    0
preco_usd_max           0
preco_usd_min           0
qtd_dias_semana         0
retorno_rs_1w           0
retorno_usd_1w          0
dtype: int64

In [9]:
cepea.isnull().sum()

indicador               0
semana                  0
preco_rs_medio          0
preco_rs_fechamento     0
preco_rs_max            0
preco_rs_min            0
preco_usd_medio         0
preco_usd_fechamento    0
preco_usd_max           0
preco_usd_min           0
qtd_dias_semana         0
retorno_rs_1w           0
retorno_usd_1w          0
dtype: int64

# **DOLAR**

In [10]:
dolar = pd.read_parquet('df_weekly-dolarptax.parquet')
dolar.head()

,dolar_medio_semana,dolar_fechamento_semana,dolar_max_semana,dolar_min_semana
data,,,,
2016-06-10,3.43638,3.4261,3.5098,3.3817
2016-06-17,3.46832,3.4372,3.4904,3.4372
2016-06-24,3.37840,3.3772,3.3897,3.3533
2016-07-01,3.28064,3.2298,3.3934,3.2098
2016-07-08,3.29964,3.2968,3.3388,3.2480

In [11]:
print(dolar.index.min(), dolar.index.max())

2016-06-10 00:00:00 2026-06-05 00:00:00

In [12]:
dolar.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 522 entries, 2016-06-10 to 2026-06-05
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   dolar_medio_semana       522 non-null    float64
 1   dolar_fechamento_semana  522 non-null    float64
 2   dolar_max_semana         522 non-null    float64
 3   dolar_min_semana         522 non-null    float64
dtypes: float64(4)
memory usage: 20.4 KB

In [13]:
dolar.shape

(522, 4)

In [14]:
print(dolar['dolar_medio_semana'].min(), dolar['dolar_medio_semana'].max())

3.08686 6.187375

In [15]:
print(dolar['dolar_fechamento_semana'].min(), dolar['dolar_fechamento_semana'].max())

3.0908 6.1991

In [16]:
print(dolar['dolar_max_semana'].min(), dolar['dolar_max_semana'].max())

3.0993 6.2086

In [17]:
print(dolar['dolar_min_semana'].min(), dolar['dolar_min_semana'].max())

3.051 6.1563

In [18]:
dolar.isna().sum()

dolar_medio_semana         0
dolar_fechamento_semana    0
dolar_max_semana           0
dolar_min_semana           0
dtype: int64

In [19]:
dolar.isnull().sum()

dolar_medio_semana         0
dolar_fechamento_semana    0
dolar_max_semana           0
dolar_min_semana           0
dtype: int64

# **COMEX**

In [20]:
comex = pd.read_parquet('fact_exports_monthly.parquet')
comex.head()

,ano_mes,volume_kg,volume_ton,valor_fob_usd,preco_implicito_usd_ton
0,2016-01-01,394419947,3.944199e+05,147623117,374.279035
1,2016-02-01,2036796148,2.036796e+06,715302008,351.189788
2,2016-03-01,8373802762,8.373803e+06,2924358377,349.227043
3,2016-04-01,10085881032,1.008588e+07,3532371105,350.229305
4,2016-05-01,9915098848,9.915099e+06,3600309132,363.113791

In [21]:
comex.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ano_mes                  125 non-null    datetime64[us]
 1   volume_kg                125 non-null    int64
 2   volume_ton               125 non-null    float64
 3   valor_fob_usd            125 non-null    int64
 4   preco_implicito_usd_ton  125 non-null    float64
dtypes: datetime64[us](1), float64(2), int64(2)
memory usage: 5.0 KB

In [22]:
comex.shape

(125, 5)

In [23]:
print(comex['ano_mes'].min(), comex['ano_mes'].max())

2016-01-01 00:00:00 2026-05-01 00:00:00

In [24]:
print(comex['ano_mes'].unique())

<DatetimeArray>
['2016-01-01 00:00:00', '2016-02-01 00:00:00', '2016-03-01 00:00:00',
 '2016-04-01 00:00:00', '2016-05-01 00:00:00', '2016-06-01 00:00:00',
 '2016-07-01 00:00:00', '2016-08-01 00:00:00', '2016-09-01 00:00:00',
 '2016-10-01 00:00:00',
 ...
 '2025-08-01 00:00:00', '2025-09-01 00:00:00', '2025-10-01 00:00:00',
 '2025-11-01 00:00:00', '2025-12-01 00:00:00', '2026-01-01 00:00:00',
 '2026-02-01 00:00:00', '2026-03-01 00:00:00', '2026-04-01 00:00:00',
 '2026-05-01 00:00:00']
Length: 125, dtype: datetime64[us]

In [25]:
comex.isna().sum()

ano_mes                    0
volume_kg                  0
volume_ton                 0
valor_fob_usd              0
preco_implicito_usd_ton    0
dtype: int64

In [26]:
comex.isnull().sum()

ano_mes                    0
volume_kg                  0
volume_ton                 0
valor_fob_usd              0
preco_implicito_usd_ton    0
dtype: int64

In [27]:
print(comex['preco_implicito_usd_ton'].min(), comex['preco_implicito_usd_ton'].max())

333.14085712913493 631.2164563296781

In [28]:
print(comex['valor_fob_usd'].min(), comex['valor_fob_usd'].max())

23266515 8115565482

In [29]:
print(comex['volume_ton'].min(), comex['volume_ton'].max())

49498.339 16756088.436

In [30]:
print(comex['volume_kg'].min(), comex['volume_kg'].max())

49498339 16756088436

# **CONAB**

In [31]:
conab = pd.read_parquet('fact_supply_safra.parquet')
conab.head()

,safra,area_mil_ha,produtividade_kg_ha,producao_mil_ton,safra_inicio,safra_fim
0,1976/77,6949.0,1747.733487,12145.0,1976,1977
1,1977/78,7780.0,1250.128535,9726.0,1977,1978
2,1978/79,8151.0,1251.380199,10200.0,1978,1979
3,1979/80,8755.9,1700.270675,14887.4,1979,1980
4,1980/81,8693.4,1781.213334,15484.8,1980,1981

In [32]:
print(conab['safra_inicio'].min(), conab['safra_fim'].max())

1976 2026

In [33]:
conab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   safra                50 non-null     object
 1   area_mil_ha          50 non-null     float64
 2   produtividade_kg_ha  50 non-null     float64
 3   producao_mil_ton     50 non-null     float64
 4   safra_inicio         50 non-null     int64
 5   safra_fim            50 non-null     int64
dtypes: float64(3), int64(2), object(1)
memory usage: 2.5+ KB

In [34]:
conab.shape

(50, 6)

In [35]:
print(conab['area_mil_ha'].min(), conab['area_mil_ha'].max())

6949.0 48716.5

In [36]:
print(conab['produtividade_kg_ha'].min(), conab['produtividade_kg_ha'].max())

1250.1285347043702 3697.5068262293066

In [37]:
print(conab['producao_mil_ton'].min(), conab['producao_mil_ton'].max())

9726.0 180129.6

# **Nasa Power**

In [38]:
weather = pd.read_parquet('fact_weather_soy_index_weekly.parquet')
weather.head()

,semana,chuva_soja_1w,temp_media_soja_1w,temp_max_soja_1w,temp_min_soja_1w,umidade_soja_1w,dias_secos_soja_1w,dias_calor_extremo_soja_1w,n_pontos,stress_chuva,stress_calor,stress_dias_secos,stress_climatico_soja
0,2016-01-01,10.3431,26.193800,29.9104,22.5117,78.542500,0.00,0.0,7,0.722936,0.170642,0.001835,0.360092
1,2016-01-08,53.8239,24.869729,30.7210,20.6299,86.791300,0.94,0.0,7,0.053211,0.278899,0.009174,0.082936
2,2016-01-15,82.1888,24.832886,29.9269,21.2143,87.844529,1.55,0.0,7,0.003670,0.177982,0.064220,0.059725
3,2016-01-22,37.4496,24.274786,30.2532,19.0845,84.233157,3.18,0.0,7,0.227523,0.214679,0.392661,0.282752
4,2016-01-29,34.2159,25.036871,30.7911,19.4414,84.769857,2.70,0.1,7,0.280734,0.289908,0.295413,0.287706

In [39]:
print(weather['semana'].min(), weather['semana'].max())

2016-01-01 00:00:00 2026-06-05 00:00:00

In [40]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   semana                      545 non-null    datetime64[us]
 1   chuva_soja_1w               545 non-null    float64
 2   temp_media_soja_1w          545 non-null    float64
 3   temp_max_soja_1w            545 non-null    float64
 4   temp_min_soja_1w            545 non-null    float64
 5   umidade_soja_1w             545 non-null    float64
 6   dias_secos_soja_1w          545 non-null    float64
 7   dias_calor_extremo_soja_1w  545 non-null    float64
 8   n_pontos                    545 non-null    int64
 9   stress_chuva                545 non-null    float64
 10  stress_calor                545 non-null    float64
 11  stress_dias_secos           545 non-null    float64
 12  stress_climatico_soja       545 non-null    float64
dtypes: datetime64[us](1), float64(11), int64(1)
memory usage: 55.5 KB

In [41]:
weather.shape

(545, 13)

In [42]:
print(weather["stress_climatico_soja"].between(0, 1).mean())
print(weather["chuva_soja_1w"].min())
print(weather["temp_max_soja_1w"].describe())

1.0
0.008
count    545.000000
mean      32.403555
std        2.525704
min       26.507800
25%       30.463500
50%       32.030100
75%       33.888600
max       40.056100
Name: temp_max_soja_1w, dtype: float64

# **calendario**

In [43]:
calendario = pd.read_parquet('df_calendario_agricola.parquet')
calendario.head()

             mes   ano fase_soja  periodo_critico_soja
data_semana
2016-01-01     1  2016  floracao                     3
2016-01-08     1  2016  floracao                     3
2016-01-15     1  2016  floracao                     3
2016-01-22     1  2016  floracao                     3
2016-01-29     1  2016  floracao                     3

In [44]:
calendario.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 544 entries, 2016-01-01 to 2026-05-29
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   mes                   544 non-null    int32
 1   ano                   544 non-null    int32
 2   fase_soja             544 non-null    object
 3   periodo_critico_soja  544 non-null    int64
dtypes: int32(2), int64(1), object(1)
memory usage: 17.0+ KB

# **Dataset**

In [45]:
START_DATE = "2016-06-10"
END_DATE = "2026-06-05"

cepea = cepea[
    cepea["semana"].between(START_DATE, END_DATE)
]

weather = weather[
    weather["semana"].between(START_DATE, END_DATE)
]

calendario = calendario[
    (calendario.index >= START_DATE) & (calendario.index <= END_DATE)
]

In [46]:
cepea_paranagua = cepea[cepea['indicador'] == 'paranagua']
cepea_paranagua.head()

,indicador,semana,preco_rs_medio,preco_rs_fechamento,preco_rs_max,preco_rs_min,preco_usd_medio,preco_usd_fechamento,preco_usd_max,preco_usd_min,qtd_dias_semana,retorno_rs_1w,retorno_usd_1w
43,paranagua,2016-06-10,96.100,96.88,96.88,95.47,28.044,28.26,28.59,27.33,5,0.006441,0.035544
45,paranagua,2016-06-17,97.100,96.78,97.61,96.16,28.026,28.28,28.28,27.72,5,-0.001032,0.000708
47,paranagua,2016-06-24,94.408,92.66,95.97,92.66,27.936,27.46,28.25,27.46,5,-0.042571,-0.028996
49,paranagua,2016-07-01,92.968,92.31,94.17,92.01,28.384,28.57,28.63,27.72,5,-0.003777,0.040422
50,paranagua,2016-07-08,90.066,87.65,92.48,87.65,27.218,26.66,28.33,26.51,5,-0.050482,-0.066853

In [47]:
dolar.head()

,dolar_medio_semana,dolar_fechamento_semana,dolar_max_semana,dolar_min_semana
data,,,,
2016-06-10,3.43638,3.4261,3.5098,3.3817
2016-06-17,3.46832,3.4372,3.4904,3.4372
2016-06-24,3.37840,3.3772,3.3897,3.3533
2016-07-01,3.28064,3.2298,3.3934,3.2098
2016-07-08,3.29964,3.2968,3.3388,3.2480

In [48]:
conab.head()

,safra,area_mil_ha,produtividade_kg_ha,producao_mil_ton,safra_inicio,safra_fim
0,1976/77,6949.0,1747.733487,12145.0,1976,1977
1,1977/78,7780.0,1250.128535,9726.0,1977,1978
2,1978/79,8151.0,1251.380199,10200.0,1978,1979
3,1979/80,8755.9,1700.270675,14887.4,1979,1980
4,1980/81,8693.4,1781.213334,15484.8,1980,1981

In [49]:
comex.head()

,ano_mes,volume_kg,volume_ton,valor_fob_usd,preco_implicito_usd_ton
0,2016-01-01,394419947,3.944199e+05,147623117,374.279035
1,2016-02-01,2036796148,2.036796e+06,715302008,351.189788
2,2016-03-01,8373802762,8.373803e+06,2924358377,349.227043
3,2016-04-01,10085881032,1.008588e+07,3532371105,350.229305
4,2016-05-01,9915098848,9.915099e+06,3600309132,363.113791

In [50]:
weather.head()

,semana,chuva_soja_1w,temp_media_soja_1w,temp_max_soja_1w,temp_min_soja_1w,umidade_soja_1w,dias_secos_soja_1w,dias_calor_extremo_soja_1w,n_pontos,stress_chuva,stress_calor,stress_dias_secos,stress_climatico_soja
23,2016-06-10,17.4756,20.509900,29.4334,11.9902,67.566800,5.41,1.1,7,0.585321,0.097248,0.672477,0.518211
24,2016-06-17,2.0682,18.883514,29.3674,9.0935,64.275414,6.74,0.3,7,0.913761,0.091743,0.937615,0.757706
25,2016-06-24,3.0711,20.825871,29.7087,13.1766,62.750443,5.92,0.7,7,0.880734,0.132110,0.760550,0.688945
26,2016-07-01,0.0401,21.803414,30.0966,14.5200,57.833271,7.00,0.4,7,0.994495,0.198165,0.990826,0.833945
27,2016-07-08,4.6174,21.514514,30.9580,12.4770,57.289343,6.39,1.8,7,0.823853,0.317431,0.855963,0.733807

In [51]:
calendario.head()

             mes   ano    fase_soja  periodo_critico_soja
data_semana
2016-06-10     6  2016  entressafra                     0
2016-06-17     6  2016  entressafra                     0
2016-06-24     6  2016  entressafra                     0
2016-07-01     7  2016  entressafra                     0
2016-07-08     7  2016  entressafra                     0

In [52]:
mart = (
    cepea_paranagua
    .merge(
        dolar.reset_index(),
        left_on="semana",
        right_on="data",
        how="inner"
    )
    .merge(
        weather,
        on="semana",
        how="inner"
    )
    .merge(
        calendario.reset_index(),
        left_on="semana",
        right_on="data_semana",
        how="inner"
    )
)

In [ ]:
mart.head()

,indicador,semana,preco_rs_medio,preco_rs_fechamento,preco_rs_max,preco_rs_min,preco_usd_medio,preco_usd_fechamento,preco_usd_max,preco_usd_min,...,n_pontos,stress_chuva,stress_calor,stress_dias_secos,stress_climatico_soja,data_semana,mes,ano,fase_soja,periodo_critico_soja
0,paranagua,2016-06-10,96.100,96.88,96.88,95.47,28.044,28.26,28.59,27.33,...,7,0.585321,0.097248,0.672477,0.518211,2016-06-10,6,2016,entressafra,0
1,paranagua,2016-06-17,97.100,96.78,97.61,96.16,28.026,28.28,28.28,27.72,...,7,0.913761,0.091743,0.937615,0.757706,2016-06-17,6,2016,entressafra,0
2,paranagua,2016-06-24,94.408,92.66,95.97,92.66,27.936,27.46,28.25,27.46,...,7,0.880734,0.132110,0.760550,0.688945,2016-06-24,6,2016,entressafra,0
3,paranagua,2016-07-01,92.968,92.31,94.17,92.01,28.384,28.57,28.63,27.72,...,7,0.994495,0.198165,0.990826,0.833945,2016-07-01,7,2016,entressafra,0
4,paranagua,2016-07-08,90.066,87.65,92.48,87.65,27.218,26.66,28.33,26.51,...,7,0.823853,0.317431,0.855963,0.733807,2016-07-08,7,2016,entressafra,0

In [53]:
mart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   indicador                   521 non-null    object
 1   semana                      521 non-null    datetime64[ns]
 2   preco_rs_medio              521 non-null    float64
 3   preco_rs_fechamento         521 non-null    float64
 4   preco_rs_max                521 non-null    float64
 5   preco_rs_min                521 non-null    float64
 6   preco_usd_medio             521 non-null    float64
 7   preco_usd_fechamento        521 non-null    float64
 8   preco_usd_max               521 non-null    float64
 9   preco_usd_min               521 non-null    float64
 10  qtd_dias_semana             521 non-null    int64
 11  retorno_rs_1w               521 non-null    float64
 12  retorno_usd_1w              521 non-null    float64
 13  data                        521 non-null    datetime64[ns]
 14  dolar_medio_semana          521 non-null    float64
 15  dolar_fechamento_semana     521 non-null    float64
 16  dolar_max_semana            521 non-null    float64
 17  dolar_min_semana            521 non-null    float64
 18  chuva_soja_1w               521 non-null    float64
 19  temp_media_soja_1w          521 non-null    float64
 20  temp_max_soja_1w            521 non-null    float64
 21  temp_min_soja_1w            521 non-null    float64
 22  umidade_soja_1w             521 non-null    float64
 23  dias_secos_soja_1w          521 non-null    float64
 24  dias_calor_extremo_soja_1w  521 non-null    float64
 25  n_pontos                    521 non-null    int64
 26  stress_chuva                521 non-null    float64
 27  stress_calor                521 non-null    float64
 28  stress_dias_secos           521 non-null    float64
 29  stress_climatico_soja       521 non-null    float64
 30  data_semana                 521 non-null    datetime64[ns]
 31  mes                         521 non-null    int32
 32  ano                         521 non-null    int32
 33  fase_soja                   521 non-null    object
 34  periodo_critico_soja        521 non-null    int64
dtypes: datetime64[ns](3), float64(25), int32(2), int64(3), object(2)
memory usage: 138.5+ KB

In [54]:
mart = mart.drop(columns=['data', 'data_semana', 'indicador', 'ano', 'stress_chuva', 'stress_calor', 'stress_dias_secos', 'preco_rs_max', 'preco_rs_min', 'preco_usd_max', 'preco_usd_min', 'qtd_dias_semana', 'dolar_max_semana', 'dolar_min_semana','temp_max_soja_1w','temp_min_soja_1w','umidade_soja_1w', 'n_pontos', 'dias_calor_extremo_soja_1w'])

In [55]:
mart.head()

,semana,preco_rs_medio,preco_rs_fechamento,preco_usd_medio,preco_usd_fechamento,retorno_rs_1w,retorno_usd_1w,dolar_medio_semana,dolar_fechamento_semana,chuva_soja_1w,temp_media_soja_1w,dias_secos_soja_1w,stress_climatico_soja,mes,fase_soja,periodo_critico_soja
0,2016-06-10,96.100,96.88,28.044,28.26,0.006441,0.035544,3.43638,3.4261,17.4756,20.509900,5.41,0.518211,6,entressafra,0
1,2016-06-17,97.100,96.78,28.026,28.28,-0.001032,0.000708,3.46832,3.4372,2.0682,18.883514,6.74,0.757706,6,entressafra,0
2,2016-06-24,94.408,92.66,27.936,27.46,-0.042571,-0.028996,3.37840,3.3772,3.0711,20.825871,5.92,0.688945,6,entressafra,0
3,2016-07-01,92.968,92.31,28.384,28.57,-0.003777,0.040422,3.28064,3.2298,0.0401,21.803414,7.00,0.833945,7,entressafra,0
4,2016-07-08,90.066,87.65,27.218,26.66,-0.050482,-0.066853,3.29964,3.2968,4.6174,21.514514,6.39,0.733807,7,entressafra,0

In [57]:
mart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   semana                   521 non-null    datetime64[ns]
 1   preco_rs_medio           521 non-null    float64
 2   preco_rs_fechamento      521 non-null    float64
 3   preco_usd_medio          521 non-null    float64
 4   preco_usd_fechamento     521 non-null    float64
 5   retorno_rs_1w            521 non-null    float64
 6   retorno_usd_1w           521 non-null    float64
 7   dolar_medio_semana       521 non-null    float64
 8   dolar_fechamento_semana  521 non-null    float64
 9   chuva_soja_1w            521 non-null    float64
 10  temp_media_soja_1w       521 non-null    float64
 11  dias_secos_soja_1w       521 non-null    float64
 12  stress_climatico_soja    521 non-null    float64
 13  mes                      521 non-null    int32
 14  fase_soja                521 non-null    object
 15  periodo_critico_soja     521 non-null    int64
dtypes: datetime64[ns](1), float64(12), int32(1), int64(1), object(1)
memory usage: 63.2+ KB

In [58]:
mart.duplicated(['semana']).sum()

np.int64(0)

In [59]:
mart_v2 = mart.copy()

mart_v2['ano_mes_semana'] = mart_v2['semana'].dt.to_period("M").dt.to_timestamp()

mart_v2['ano_mes_comex_ref'] = mart_v2['ano_mes_semana'] - pd.DateOffset(months=1)

comex_selected = comex[
    [
        "ano_mes",
        "volume_ton",
        "valor_fob_usd",
        "preco_implicito_usd_ton"
    ]
].copy()

comex_selected = comex_selected.rename(
    columns={
        "ano_mes": "ano_mes_comex_ref",
        "volume_ton": "export_volume_ton_lag_1m",
        "valor_fob_usd": "export_valor_fob_usd_lag_1m",
        "preco_implicito_usd_ton": "export_preco_implicito_usd_ton_lag_1m"
    }
)

mart_v2 = mart_v2.merge(
    comex_selected,
    on="ano_mes_comex_ref",
    how="left"
)

def get_safra_inicio(data):
    ano = data.year
    mes = data.month

    if mes >= 9:
        return ano
    else:
        return ano - 1


def format_safra(safra_inicio):
    safra_fim = safra_inicio + 1
    return f"{safra_inicio}/{str(safra_fim)[-2:]}"


mart_v2["safra_inicio_ref"] = mart_v2["semana"].apply(get_safra_inicio)
mart_v2["safra_ref"] = mart_v2["safra_inicio_ref"].apply(format_safra)

conab_selected = conab[
    [
        "safra",
        "area_mil_ha",
        "produtividade_kg_ha",
        "producao_mil_ton"
    ]
].copy()

conab_selected = conab_selected.rename(
    columns={
        "safra": "safra_ref",
        "area_mil_ha": "conab_area_mil_ha",
        "produtividade_kg_ha": "conab_produtividade_kg_ha",
        "producao_mil_ton": "conab_producao_mil_ton"
    }
)

mart_v2 = mart_v2.merge(
    conab_selected,
    on="safra_ref",
    how="left"
)

cols_to_drop = [
    "ano_mes_semana",
    "ano_mes_comex_ref",
    "safra_inicio_ref",
]

mart_v2 = mart_v2.drop(columns=cols_to_drop)


print("Shape:", mart_v2.shape)
print("Período:", mart_v2["semana"].min(), "até", mart_v2["semana"].max())
print("Duplicatas semana:", mart_v2.duplicated(["semana"]).sum())

print("\nNulos:")
print(mart_v2.isna().sum().sort_values(ascending=False))

Shape: (521, 23)
Período: 2016-06-10 00:00:00 até 2026-05-29 00:00:00
Duplicatas semana: 0

Nulos:
semana                                   0
preco_rs_medio                           0
preco_rs_fechamento                      0
preco_usd_medio                          0
preco_usd_fechamento                     0
retorno_rs_1w                            0
retorno_usd_1w                           0
dolar_medio_semana                       0
dolar_fechamento_semana                  0
chuva_soja_1w                            0
temp_media_soja_1w                       0
dias_secos_soja_1w                       0
stress_climatico_soja                    0
mes                                      0
fase_soja                                0
periodo_critico_soja                     0
export_volume_ton_lag_1m                 0
export_valor_fob_usd_lag_1m              0
export_preco_implicito_usd_ton_lag_1m    0
safra_ref                                0
conab_area_mil_ha                        0
conab_produtividade_kg_ha                0
conab_producao_mil_ton                   0
dtype: int64

In [60]:
mart_v2.head()

,semana,preco_rs_medio,preco_rs_fechamento,preco_usd_medio,preco_usd_fechamento,retorno_rs_1w,retorno_usd_1w,dolar_medio_semana,dolar_fechamento_semana,chuva_soja_1w,...,mes,fase_soja,periodo_critico_soja,export_volume_ton_lag_1m,export_valor_fob_usd_lag_1m,export_preco_implicito_usd_ton_lag_1m,safra_ref,conab_area_mil_ha,conab_produtividade_kg_ha,conab_producao_mil_ton
0,2016-06-10,96.100,96.88,28.044,28.26,0.006441,0.035544,3.43638,3.4261,17.4756,...,6,entressafra,0,9915098.848,3600309132,363.113791,2015/16,33251.9,2877.958999,95697.60484
1,2016-06-17,97.100,96.78,28.026,28.28,-0.001032,0.000708,3.46832,3.4372,2.0682,...,6,entressafra,0,9915098.848,3600309132,363.113791,2015/16,33251.9,2877.958999,95697.60484
2,2016-06-24,94.408,92.66,27.936,27.46,-0.042571,-0.028996,3.37840,3.3772,3.0711,...,6,entressafra,0,9915098.848,3600309132,363.113791,2015/16,33251.9,2877.958999,95697.60484
3,2016-07-01,92.968,92.31,28.384,28.57,-0.003777,0.040422,3.28064,3.2298,0.0401,...,7,entressafra,0,7761036.427,2971369089,382.857253,2015/16,33251.9,2877.958999,95697.60484
4,2016-07-08,90.066,87.65,27.218,26.66,-0.050482,-0.066853,3.29964,3.2968,4.6174,...,7,entressafra,0,7761036.427,2971369089,382.857253,2015/16,33251.9,2877.958999,95697.60484

In [61]:
mart_v2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 23 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   semana                                 521 non-null    datetime64[ns]
 1   preco_rs_medio                         521 non-null    float64
 2   preco_rs_fechamento                    521 non-null    float64
 3   preco_usd_medio                        521 non-null    float64
 4   preco_usd_fechamento                   521 non-null    float64
 5   retorno_rs_1w                          521 non-null    float64
 6   retorno_usd_1w                         521 non-null    float64
 7   dolar_medio_semana                     521 non-null    float64
 8   dolar_fechamento_semana                521 non-null    float64
 9   chuva_soja_1w                          521 non-null    float64
 10  temp_media_soja_1w                     521 non-null    float64
 11  dias_secos_soja_1w                     521 non-null    float64
 12  stress_climatico_soja                  521 non-null    float64
 13  mes                                    521 non-null    int32
 14  fase_soja                              521 non-null    object
 15  periodo_critico_soja                   521 non-null    int64
 16  export_volume_ton_lag_1m               521 non-null    float64
 17  export_valor_fob_usd_lag_1m            521 non-null    int64
 18  export_preco_implicito_usd_ton_lag_1m  521 non-null    float64
 19  safra_ref                              521 non-null    object
 20  conab_area_mil_ha                      521 non-null    float64
 21  conab_produtividade_kg_ha              521 non-null    float64
 22  conab_producao_mil_ton                 521 non-null    float64
dtypes: datetime64[ns](1), float64(17), int32(1), int64(2), object(2)
memory usage: 91.7+ KB

In [64]:
mart_v2.to_parquet('base.parquet')